substitutions:
  _DOCUMENT_PATH:     "ai-lawyers-influencers-vector-store/docs"
  _CHROMA_DIR:        "/tmp/chroma"
  _CHROMA_DB_URL: "_REPLACE_WITH_AIVEN_CHROMA_URL"
  _AUTH_DB_URL: "_REPLACE_WITH_AIVEN_CHROMA_URL"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ── 1) Fetch project number and write to workspace ─────────────────────────────
  - id: "get-project-number"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
          PROJECT_NUMBER=$(gcloud projects describe "$PROJECT_ID" \
            --format="value(projectNumber)")
          echo "PROJECT_NUMBER=$PROJECT_NUMBER" > /workspace/project_number.env

  # ── 7) Build & Push Docker Image ───────────────────────────────────────────────
  - id: "build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ai-lawyers-influencers", "."]

  - id: "push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ai-lawyers-influencers"]

  # ── 8) Deploy to Cloud Run ──────────────────────────────────────────────────────
  - id: "deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
          # bring PROJECT_NUMBER into scope
          source /workspace/project_number.env

          gcloud run deploy ai-lawyers-influencers \
            --image gcr.io/$PROJECT_ID/ai-lawyers-influencers \
            --platform managed \
            --region us-central1 \
            --memory=2Gi \
            --allow-unauthenticated \
            --set-env-vars=PROJECT_NUMBER=$PROJECT_NUMBER,AUTH_DB_URL=${_AUTH_DB_URL},CHROMA_DB_URL=${_CHROMA_DB_URL},CHROMA_DIR=${_CHROMA_DIR},DOCUMENT_PATH=${_DOCUMENT_PATH}


            